# -*- coding: utf-8 -*-
"FileTrack String Resources"
from porcupine.config.resources import ResourceStrings, Locale

resources = ResourceStrings({
    '*' : Locale({
        'schemas.org.innoscript.filetrack.LogEntries' : 'Log', 
        'schemas.org.innoscript.filetrack.LogEntry' : 'Log entry',
        'schemas.org.innoscript.filetrack.Issue' : 'Issue',
        'schemas.org.innoscript.filetrack.LogArchiveSet' : 'Archive Folder',
        'schemas.org.innoscript.collab.Contact' : 'Contact',
        
        'entryDate' : 'Date sent/received',
        'entryType' : 'Document type',
        'aa' : 'Α/Α',
        'sender' : 'Sender',
        'receiver' : 'Receiver',
        'cc' : 'Carbon Copy',
        'senderDate' : 'Sender date',
        'senderCode' : 'Sender protocol number',
        'logEntryDocuments' : 'Files',
        'comments' : 'Comments',
        'currentOwner' : 'Current owner',
        'issues' : 'Issues',
        'issueStatus' : 'Status',
        'issueClosed' : 'Issue closed',
        'issueItems' : 'Issue items',
        'displayName' : 'Name',
        'description' : 'Description',
        'categories' : 'Categories',
        'company' : 'Company',
        'email' : 'e-mail',

        'FILE' : 'File',
        'TOOLS' : 'Tools',
        'INFO' : 'Info',
        'MENU_NEW' : 'Create',
        'SEARCH' : 'Search',
        'DELETE' : 'Delete',
        'ISSUES' : 'Issues',
        'ADD' : 'Add',
        'REMOVE' : 'Remove',
        'UPDATE' : 'Update',
        'CLOSE' : 'Close',
        'CONTAINS' : 'contains',
        'DATEMOD' : 'Date modified',
        'FROM' : 'from',
        'TO' : 'to',
        'SORTORDER' : 'Sort order',
        'SORTFIELD' : 'Sort field',
        'ASC' : 'ascending',
        'DESC' : 'descending',
        'EXIT' : 'Exit',
        'OPTIONS' : 'Options',
        'OK' : 'OK',
        'CANCEL' : 'Cancel',
        'RENAME' : 'Rename',
        'ERROR' : 'Error',
        'YES' : 'Yes',
        'NO' : 'No',
        
        'CREATE' : 'Create',
        'REFRESH' : 'Refresh',
        'FILTER' : 'Filter',
        'PROPERTIES' : 'Properties',
        'ABOUT_FILETRACK' : 'About FileTrack',
        'NEW_PROTOCOL_ENTRY' : 'Create new entry',
        'LOGS' : 'Logs',
        'SHORTCUTS' : 'Shortcuts',
        'INBOUND' : 'Inbound',
        'OUTBOUND' : 'Outbound',
        'PROTOCOL_NO' : 'Code',
        'CONTACTS' : 'Contacts',
        'SURNAME' : 'Surname',
        'RECORDS' : 'Records',
        'ISSUE_OPEN' : 'Open',
        'ISSUE_CLOSED' : 'Closed',
        'REPLY' : 'Reply',
        'REPLY_TO' : 'Reply to',
        'REPORTS' : 'Reports',
        'PROTOCOL_REPORT' : 'Protocol Report',
        'REPORT_CRITERIA' : 'Report criteria',
        'SHOW_ALL' : 'Show all',
        'SHOW_INCOMING' : 'Show incoming',
        'SHOW_OUTGOING' : 'Show outgoing',
        'SHOW_OPEN' : 'Show open',
        'SHOW_CLOSED' : 'Show closed',
        'PAGE_SIZE' : 'Page size',
        'GO_TO_PAGE' : 'Go to page',
        'MAX_SEARCH_RES' : 'Max search results',
        'SELECT_SET' : 'Select folder',
        'DO_ARCHIVE' : 'Archive',
        'ARCHIVE_WARNING' : 'WARNING: This action is irreversible!',
        'FILETRACK_WARNING' : 'Warning',
        'FILETRACK_DISPLAYING' : 'Displaying',
        'FILETRACK_ASK_DELETE' : 'Are you sure you want to delete the selected items?',
        'QUEST_RESET_COUNTERS' : 'Are you sure?',
        'RESET_COUNTERS' : 'Reset numbering',
        'RESET_COUNTERS_OK' : 'Log numbers have been successfully reset.',
        'AUTO_ARCHIVE' : 'Auto archive',
        'SEARCH_SCOPE' : 'Search scope',
        'SEARCH_ARCHIVE' : 'Search archive',
        'WARN_SELECT_SCOPE' : 'Please select one ore more search scopes.',
        'WARN_SELECT_DEST_SET' : 'Please select a destination set.',
        'GENERATE_REPORT' : 'Generate report',
        'INDEX_BY_NAME' : 'Index by name',
        'INDEX_BY_COMPANY' : 'Index by company'
    }),
    'el' : Locale({
        'schemas.org.innoscript.filetrack.LogEntries' : 'Πρωτόκολλο',
        'schemas.org.innoscript.filetrack.LogEntry' : 'Εγγραφή πρωτοκόλλου', 
        'schemas.org.innoscript.filetrack.Issue' : 'Θέμα',
        'schemas.org.innoscript.filetrack.LogArchiveSet' : 'Φάκελος αρχειοθέτησης',
        'schemas.org.innoscript.collab.Contact' : 'Επαφή',
        
        'entryDate' : 'Ημ/νία παραλαβής/αποστολής',
        'entryType' : 'Είδος εγγράφου',
        'aa' : 'Α/Α',
        'sender' : 'Αποστολέας',
        'receiver' : 'Παραλήπτης',
        'cc' : 'Κοινοποίηση',
        'senderDate' : 'Ημερομηνία αποστολέα',
        'senderCode' : 'Αριθμός πρωτοκόλλου αποστολέα',
        'logEntryDocuments' : 'Αρχεία',
        'comments' : 'Σχόλια',
        'currentOwner' : 'Κάτοχος',
        'issues' : 'Θέματα',
        'issueStatus' : 'Κατάσταση',
        'issueClosed' : 'Έκλεισε',
        'issueItems' : 'Αντικείμενα θέματος',
        'displayName' : 'Όνομα',
        'description' : 'Περιγραφή',
        'categories' : 'Κατηγορίες',
        'company' : 'Εταιρεία',
        'email' : 'e-mail',

        'FILE' : 'Αρχείο',
        'TOOLS' : 'Εργαλεία',
        'INFO' : 'Πληροφορίες',
        'MENU_NEW' : 'Δημιουργία',
        'SEARCH' : 'Αναζήτηση',
        'DELETE' : 'Διαγραφή',
        'ISSUES' : 'Θέματα',
        'ADD' : 'Προσθήκη',
        'REMOVE' : 'Αφαίρεση',
        'UPDATE' : 'Ενημέρωση',
        'CLOSE' : 'Κλείσιμο',
        'CONTAINS' : 'περιέχει',
        'DATEMOD' : 'Ημ/νία τροποποίησης',
        'FROM' : 'από',
        'TO' : 'έως',
        'SORTORDER' : 'Σειρά ταξινόμισης',
        'SORTFIELD' : 'Πεδίο ταξινόμισης',
        'ASC' : 'αύξουσα',
        'DESC' : 'φθίνουσα',
        'EXIT' : 'Έξοδος',
        'OPTIONS' : 'Επιλογές',
        'OK' : 'Εντάξει',
        'CANCEL' : 'Άκυρο',
        'RENAME' : 'Μετονομασία',
        'ERROR' : 'Λάθος',
        'YES' : 'Ναι',
        'NO' : 'Όχι',
        
        'CREATE' : 'Δημιουργία',
        'REFRESH' : 'Ανανέωση',
        'FILTER' : 'Φίλτρο',
        'PROPERTIES' : 'Ιδιότητες',
        'ABOUT_FILETRACK' : 'Σχετικά με το FileTrack',
        'NEW_PROTOCOL_ENTRY' : 'Δημιουργία νέας εγγραφής',
        'LOGS' : 'Πρωτόκολλα', 
        'SHORTCUTS' : 'Συντομεύσεις', 
        'INBOUND' : 'Εισερχόμενο',
        'OUTBOUND' : 'Εξερχόμενο', 
        'PROTOCOL_NO' : 'Αρ. Πρωτοκόλλου',
        'CONTACTS' : 'Επαφές',
        'SURNAME' : 'Ονοματεπώνυμο',
        'RECORDS' : 'Εγγραφές',
        'ISSUE_OPEN' : 'Ανοικτό',
        'ISSUE_CLOSED' : 'Κλειστό',
        'REPLY' : 'Απάντηση',
        'REPLY_TO' : 'Απάντηση στο',
        'REPORTS' : 'Αναφορές',
        'PROTOCOL_REPORT' : 'Αναφορά Πρωτοκόλλου',
        'REPORT_CRITERIA' : 'Κριτήρια αναφοράς',
        'SHOW_ALL' : 'Εμφανιση όλων',
        'SHOW_INCOMING' : 'Εμφάνιση εισερχόμενων',
        'SHOW_OUTGOING' : 'Εμφάνιση εξερχόμενων',
        'SHOW_OPEN' : 'Εμφάνιση ανοικτών', 
        'SHOW_CLOSED' : 'Εμφάνιση κλειστών',
        'PAGE_SIZE' : 'Μέγεθος σελίδας',
        'GO_TO_PAGE' : 'Μετάβαση στη σελίδα',
        'MAX_SEARCH_RES' : 'Όριο αποτελεσμάτων αναζήτησης',
        'SELECT_SET' : 'Επιλέξτε φάκελο', 
        'DO_ARCHIVE' : 'Αρχειοθέτηση',
        'ARCHIVE_WARNING' : 'ΠΡΟΣΟΧΗ: Η αρχειοθέτηση είναι μη αναστρέψιμη ενέργεια',
        'FILETRACK_WARNING' : 'Προσοχή',
        'FILETRACK_DISPLAYING' : 'Εμφανίζονται',
        'FILETRACK_ASK_DELETE' : 'Είστε σίγουροι ότι θέλετε να διαγράψετε τα επιλεγμένα αντικείμενα;', 
        'QUEST_RESET_COUNTERS' : 'Είστε σίγουροι;',
        'RESET_COUNTERS' : 'Αρχικοποίηση αρίθμησης',
        'RESET_COUNTERS_OK' : 'Η αρίθμηση του πρωτοκόλλου αρχικοποιήθηκε επιτυχώς.',
        'AUTO_ARCHIVE' : 'Αυτόματη αρχειοθέτηση',
        'SEARCH_SCOPE' : 'Τομείς αναζήτησης',
        'SEARCH_ARCHIVE' : 'Αναζήτηση στο αρχείο',
        'WARN_SELECT_SCOPE' : 'Παρακαλώ επιλέξτε έναν ή περισσότερους τομείς αναζήτησης.',
        'WARN_SELECT_DEST_SET' : 'Παρακαλώ επιλέξτε έναν προορισμό αρχειοθέτησης.',
        'GENERATE_REPORT' : 'Δημιουργία αναφοράς',
        'INDEX_BY_NAME' : 'Κατηγοριοποίηση ανά όνομα',
        'INDEX_BY_COMPANY' : 'Κατηγοριοποίηση ανά εταιρεία'
    })
})